### ISSUE TITLE
Basic UI

### ISSUE THREAD

**Issue by vvasuki** [sanskrit/ashtadhyayi#10]
We now have a basic UI based on the Hugo static site generator. See https://sanskrit.github.io/ashtadhyayi/nyasa/pada-1.1/1.1.1/ for example.

Please feel free to improve it.

**Comment by chandrasekharanr** [comment]
Can the edits be directly done in the UI (using the edit option)? If yes, can I start making the edits there. 

One thing I am not sure is whether the edits will overwrite the master or not. If it does overwrite, how do we do version control? What if we want to go back to the older version?

Or, should I create a different branch and edit it in that branch and we merge it to the mainline using pull requests? I know that this way we have version control.

**Comment by vvasuki** [comment]
clicking on edit will take a person to github, where one clicks the ✏️ icon and make changes as usual. in case one has write permissions to the repo, one can directly save the changes. otherwise pull request is used to submit the changes to repo maintainers for merging.

**Comment by drdhaval2785** [comment]
I have been closely associated with correction system at Cologne servers which do corrections on 36 dictionaries related to Sanskrit. I feel that their system for correction is quite robust. All changes made hitherto have been documented with submitter, timestamp, old, new versions etc. See https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/correctionform.txt for details.

We may adopt the same standard modified to our purpose. That would be much better.

**Comment by drdhaval2785** [comment]
One more suggestion. 

Some of the users who may submit corrections are not tech savvy. We should have a frontend where the user can input necessary fields, we autopopulate text in OLD, NEW text areas and the user submits the corrected one via HTML frontend rather than the git way. 

https://www.sanskrit-lexicon.uni-koeln.de/php/correction_form.php?dict=MW modified to our purpose would be just fine. When a person clicks on nyasa/pada-1.1/1.1.1 for edit, we can autopopulate the text of nyasa 1.1.1 in text area of OLD and NEW.

Fields in my opinion 
1. Commentary name (autofilled)
2. Sutra number (autofilled)
3. Old text (autofilled)
4. Corrected text (autofilled)
5. Notes or comments

If 3 and 4 are the same on submit, we give an error.

If 3 and 4 are the same while

**Comment by chandrasekharanr** [comment]
Agree with this idea. The only caveat is that the user should not have to type a lot for suggesting a missing अकारः (or any such simple correction). I like the idea of auto filling most of the obvious fields.

**Comment by vvasuki** [comment]
> All changes made hitherto have been documented with submitter, timestamp, old, new versions etc. See https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/correctionform.txt for details.

@drdhaval2785 - What benefit does such a record add beyond git records? (Ignoring the presentation aspect - like the ability to tell others "see how much we've improved it")

**Comment by drdhaval2785** [comment]
Oh. Many advantages. 

1. There are cases when some user submitted some wrong correction. We unintentionally approved the same. Now when we want to find out erring entry, nobody would read git commits who are not necessarily named consistently. One single file of correction would definitely help locate this easily.
2. User who submitted the correction would be duly acknowledged for his help.

**Comment by vvasuki** [comment]
>‌  Now when we want to find out erring entry, nobody would read git commits who are not necessarily named consistently. One single file of correction would definitely help locate this easily.

Sounds like a (suboptimal) reinvention of the [git blame feature](https://help.github.com/articles/tracking-changes-in-a-file/).

Separately, moved the UI to https://ashtadhyayi.github.io/ui/vritti/nyasa/pada-1.1/1.1.1/ and scripts also to a [separate repository](https://github.com/ashtadhyayi/data_curation). Henceforth this repo will strictly contain *only* vritti data and nothing else - so that one may use it as a git submodule in a variety of projects in a variety of languages. Invited dhaval to the new ashtadhyayi org.

**Comment by drdhaval2785** [comment]
Never knew git blame existed. No complaints. We can use git blame. I withdraw my comments regarding changelog.

**Comment by drdhaval2785** [comment]
My suggestion for frontend still continues.

**Comment by chandrasekharanr** [comment]
@vvasuki, would it be possible to provide a "Next" with hyperlink to the next sutra in the UI? It will be very useful.

**Comment by vvasuki** [comment]
@chandrasekharanr  Done - added a search box as well.

@drdhaval2785 The correction form idea would require us to have our own server to be fully automatic. An alternative is for you or @chandrasekharanr to set up a google form (similar to http://ashtadhyayi.com/sutraani/6/1/114 ) which you can manually and periodically use as basis for then doing proper git corrections.

**Comment by vvasuki** [comment]
Set up a combined view as well - http://localhost:1313/ui/?sutra=2.2.12

**Comment by drdhaval2785** [comment]
There is no 'go' button on the search box. Not possible to trigger.

**Comment by vvasuki** [comment]
> There is no 'go' button on the search box. Not possible to trigger.

Press "Enter"

**Comment by drdhaval2785** [comment]
In my samsung s8+ mobile, i pressed enter. Nothing happens.

**Comment by drdhaval2785** [comment]
Autopopulation in search box also makes my mobile hang for 3-4 seconds.

**Comment by vvasuki** [comment]
Added a search button.

The hanging should not happen after the first search (when the sutra list is downloaded for autocompletion) - check and let me know.

**Comment by chandrasekharanr** [comment]
Why is it not displaying tattvabodhini?

**Comment by vvasuki** [comment]
इदानीं दर्शयति। महाभाष्यमपि।

**Comment by vvasuki** [comment]
शिष्टास् समस्या अस्य सम्बन्धे https://github.com/ashtadhyayi/ui/issues इत्यत्र ज्ञापनीयाः।

**Comment by gasyoun** [comment]
https://sanskrit.github.io/ashtadhyayi/nyasa/pada-1.1/1.1.1/  broken.

**Comment by vvasuki** [comment]
wrong link. try https://ashtadhyayi.github.io/sutra-details/?sutra=1.1.1
