### ISSUE TITLE
Sources for editing the contents

### ISSUE THREAD

**Issue by chandrasekharanr** [sanskrit/ashtadhyayi#12]
One thing we have to agree upon is the master source from where we are editing the contents of all these vRttis. Here are my sources --

1.  काशिकावृत्तिः -- by विजगोपलो विद्यावारिधिः (Ramlal Kapoor Trust publication)
2.  बालमनोरमा / तत्त्वबोधिनी -- वैयाकरणसिद्धन्तकौमुदी -- बालमनोरमा-तत्त्वबोधिनीसहिता (MLBD 4 volume book)

Right now, I am going to work only on the above three.

**Comment by drdhaval2785** [comment]
There are bound to be some differences in editions. Let us not try to correct those small differences. Let us correct only if it is grammatically or typologically incorrect.

**Comment by drdhaval2785** [comment]
What is your take @vvasuki and @chandrasekharanr?

**Comment by vvasuki** [comment]
I agree with dhaval about ignoring insignificant deviations - and I'd be surprised if there actually exist significant differences. Where such differences are significant, we should decide on a case-by-case basis.

**Comment by chandrasekharanr** [comment]
Agree with @vvasuki
