### ISSUE TITLE
Incomplete vRtti in bAlamanoramA

### ISSUE THREAD

**Issue by chandrasekharanr** [sanskrit/ashtadhyayi#14]
Checked a couple of vRttis in bAlamanoramA, 
e.g., 
https://sanskrit.github.io/ashtadhyayi/balamanorama/pada-6.1/6.1.114/
https://sanskrit.github.io/ashtadhyayi/balamanorama/pada-8.3/8.3.17/

Both are incomplete. Source with complete versions should be available, since avg-sanskrit has it right --
http://avg-sanskrit.org/sutras/6-1-114.html
http://avg-sanskrit.org/sutras/8-3-17.html

Can we update the source, before I make the changes?

**Comment by chandrasekharanr** [comment]
Here is the link for avg-sanskrit repository, if needed : https://github.com/chandrasekharanr/avg-sanskrit-sutras

**Comment by drdhaval2785** [comment]
Please update using complete vrittis. We have not yet made much changes.

**Comment by chandrasekharanr** [comment]
@vvasuki - please update the bAlamanoramA.

Thanks!

**Comment by vvasuki** [comment]
Updated from ashtadhyayi.org . Fixes some missing entries. Still has some empty entries, though.
