### ISSUE TITLE
Missing pada-6.2 in Balamanorama

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit/ashtadhyayi#15]
I earlier thought that only tattvabodhini 6.2 is missing. It turns out that pada 6.2 is missing in whole gamut.

**Comment by neeleshb** [comment]
That's because BM and TB aren't simply written down for those sutras.

There is no balamanorama and tattva bodhini written for the swara prakaran of ashtadhyayi, which is any sutra at or after SK3650

**Comment by drdhaval2785** [comment]
Ok. That explains.
