### ISSUE TITLE
period(.) --> virAmachihnam (|) in laghu

### ISSUE THREAD

**Issue by chandrasekharanr** [sanskrit/ashtadhyayi#16]
In the laghu vRtti, need to replace all period (.) with | 

And all double period (..) with ||

This updated repository is probably already available. In my phone, I see this change already (used stardict dictionary updater by @vvasuki )

**Comment by vvasuki** [comment]
@neeleshb - त्वज्जालक्षेत्रे परिष्कृततरं दृश्यते लघुसिद्धान्तकौमुदी - तदपि तव api-मध्ये योजय सदयम्।

**Comment by neeleshb** [comment]
Available under "lsk" and "lskn" key.
