### ISSUE TITLE
Add satishji's notes as a "vritti" to this repo?

### ISSUE THREAD

**Issue by vvasuki** [sanskrit/ashtadhyayi#17]

**Comment by chandrasekharanr** [comment]
I will use Python. Thanks for the lead.

**Comment by chandrasekharanr** [comment]
Uploaded Satishji's notes (scrapped from avg-sanskrit site) here --

https://github.com/chandrasekharanr/avg-sanskrit-sutras/tree/master/Satishji-s%20Notes

Anything else needed from me?

@vvasuki , can you please upload it in the sutra repo and add them to the UI?

**Comment by vvasuki** [comment]
Nice! Can you just delete those TBD files and add them when you actually enter the notes?

**Comment by vvasuki** [comment]
And also replace sutra numberings like 7-3-103 with 7.3.103 (just use regular expression replacement in your favorite mass editing tool)

**Comment by vvasuki** [comment]
(तथा, "80) ह्रस्वस्य गुण: 7-3-108 " इत्यादिभ्य आदिमसङ्ख्यां निष्कास्य "ह्रस्वस्य गुण: 7-3-108" इतिवत् क्रियताम्।

**Comment by vvasuki** [comment]
Also, I think it's better to generate markdown files so as to preserve the formatting.

**Comment by chandrasekharanr** [comment]
आदिष्टानि सर्वाणि कार्याणि कृतानि । परिशील्यत्विति प्रार्थये ।

https://github.com/chandrasekharanr/avg-sanskrit-sutras/tree/master/Satishji-s%20Notes

**Comment by vvasuki** [comment]
प्रत्येकस्यां सञ्चिकायाम् आदौ YAML-भाषया metadataसुचना अपेक्ष्यन्ते। उदाहरणम् -
```
---
index: 1.1.1
sutra: वृद्धिरादैच्
vritti: satishabodha
---
```

**Comment by chandrasekharanr** [comment]
Done, and updated the repo.

(Thanks : data_curation/ashtadhyayi_data/repo_writer/__init__.py)

**Comment by vvasuki** [comment]
साधु! अहं "वृत्तिः --ः" इतिवद् दूष्टविसर्गान् ईक्षे। तान् निष्कास्य "ashtadhyayi"-कोशे satishabodha इत्यस्मिन् सर्वास् सञ्चिकास् स्थापयतु।

**Comment by chandrasekharanr** [comment]
https://github.com/sanskrit/ashtadhyayi/tree/master/satishabodha

**Comment by vvasuki** [comment]
ॐ। अधुना यथा दृश्येत तथाकरवम्।
