### ISSUE TITLE
Typos in some ashtadhyayi.com data

### ISSUE THREAD

**Issue by vvasuki** [sanskrit/ashtadhyayi#19]
mitra @neeleshb  - https://github.com/sanskrit/ashtadhyayi/commit/f13b75bbb3e663c4aee65056b04387a2b429acad इतीक्षस्व। प्रायेणैवं तव जालकोशेऽपि शोधयितुमिच्छेः।

एवं ।-चिह्नस्य स्थाने |-इति कारणेनैव प्रयुक्तम्?

**Comment by neeleshb** [comment]
अनेके धन्यवादाः ।  ashtadhyayi.com इत्यत्र
(:) इत्यस्य स्थाने ( ः) इति परिष्कृतम् । 
(|) इत्यस्य स्थाने (।) इत्यपि । 
json will now give the correct data.
