### ISSUE TITLE
Link to Sutra indices in Siddhantakaumudi

### ISSUE THREAD

**Issue by chandrasekharanr** [sanskrit/ashtadhyayi#25]
Need to link sutra indices in Siddhantakaumudi :

Example here (need link to <{307}>) --

इन्नादीनामुपधाया दीर्घः स्यादसंबुद्धौ सौ परे । वृत्रहा । हे वृत्रहन् । एकाजुत्तरपदे **<{307}>** इति णत्वम् । वृत्रहणौ । वृत्रहणः । वृत्रहणम् । वृत्रहणौ ॥

https://ashtadhyayi.github.io/ui/vritti/siddhantakaumudi/pada-6.4/6.4.13/

**Comment by vvasuki** [comment]
Question - Is the sutra पूर्णसूत्रसङ्ख्या to कौमुदीक्रमसङ्ख्या map
 from the eponymous columns in [this spreadsheet](https://docs.google.com/spreadsheets/d/1208pyOsYiZlS5fmm8tYEq2qbCzqWgPnMYNUf1-1uRJM/edit#gid=0) reliable?

(cc: @drdhaval2785 @neeleshb )

Seems like the following oddities (duplication and omission) exists:

```
$ sort tmp/tmp.csv -k2,2 |uniq -d -f1 |sort
1.2.17	2389
1.4.15	2651
1.4.16	2252
1.4.20	3370
1.4.6	293
2.1.25	678
2.1.53	731
2.1.70	751
2.4.35	2632
2.4.51	2571
3.1.22	2629
3.1.54	2419
3.1.55	2343
4.1.166
4.2.145	1369
4.3.13	1383
4.3.9	1379
4.4.106	3455
4.4.127	3473
5.1.118	3496
5.1.91	3493
5.3.111	3502
6.1.136	2539
6.1.14	1004
6.1.54	2569
6.1.65	2268
6.3.108	3550
6.4.104	2329
6.4.34	2486
6.4.46	3307
7.1.18	287
7.2.35	3584
7.2.43	2526
7.3.30	140
7.3.86	2181
```

**Comment by vvasuki** [comment]
![image](https://user-images.githubusercontent.com/2664797/51295289-ca06a780-19cb-11e9-8bdd-4fcd6a3fbb83.png)
