### ISSUE TITLE
Nyasa regeneration

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit/ashtadhyayi#27]
https://github.com/drdhaval2785/nyasa_regen/tree/master/md has the MD files regenerated from Wilbourhall sansknet files. Seem to be much cleaner than earlier nyasa files. Request @vvasuki and others to have a look. Then I will merge them in sanskrit/ashtadhyayi repo.

Known issue - https://github.com/drdhaval2785/nyasa_regen/issues

**Comment by vvasuki** [comment]
Tagging @chandrasekharanr @neeleshb

**Comment by drdhaval2785** [comment]
Now the known issue of 'u' is also resolved.

Create a diff of existing nyasa and regenerated one. 
Some corrections etc may have been made in rule number etc.
Note it and then shift the data to this repository.
Rest of the corrections may be done here.

**Comment by drdhaval2785** [comment]
Majority of the corrections have been merged with this repo.
Now individual corrections can be handled separately via new issues.
