### ISSUE TITLE
Make this repo the master for stardict-sanskrit

### ISSUE THREAD

**Issue by chandrasekharanr** [sanskrit/ashtadhyayi#28]
Need to make this repo the absolute master. The changes made here should be reflected in the below stardict repo as well  --

https://github.com/sanskrit-coders/stardict-sanskrit/tree/master/sa-vyAkaraNa

**Comment by vvasuki** [comment]
Closing and tracking at https://github.com/sanskrit-coders/stardict-sanskrit/issues/96 instead.
