### ISSUE TITLE
wercker error of improper YAML

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit/ashtadhyayi#31]
`Error: Error building site: "/pipeline/source/content/vritti/nyasa/pada-4.3/4.3.75.md:3:1": failed to unmarshal YAML: yaml: line 2: found character that cannot start any token`

main issue is backtick character.

**Comment by vvasuki** [comment]
Fixed now (I think).

mitra @drdhaval2785 - let's not check in YAML errors which block site rebuilds (and thus may discourage user contributions).

**Comment by drdhaval2785** [comment]
It was not posted for discouraging user contribution. It was posted as a reminder for myself that there are some errorrs in conversion process. The YAML had backtick instead of Tha.

**Comment by vvasuki** [comment]
Github issues are fine - I was saying be wary of letting the build fail for too long since the latter (not the former) might dampen correcter enthusiasm.
