### ISSUE TITLE
Icon?

### ISSUE THREAD

**Issue by himanshucanberra** [sanskrit/ashtadhyayi#41]
A very silly suggestion but it will help if you had a display icon with avg web pages. I normally keep it as one of the open tabs in my browser and without an icon it's difficult to identify the site. 

Many many thanks for the great material you make available. Thanks.

**Comment by vvasuki** [comment]
Added the favicon icon to https://ashtadhyayi.github.io/ui/ . 

For avg sites, @chandrasekharanr might be able to help.
