### ISSUE TITLE
Wrong sutra id: सि.कौ. 8136

### ISSUE THREAD

**Issue by chandrasekharanr** [sanskrit/ashtadhyayi#43]
In one of the pages (3.1.134), the SK vrtti is not showing up in the UI --
https://ashtadhyayi.github.io/sutra-details/?sutra=3.1.134

Checked that this file is available in the repository. 
https://github.com/sanskrit/ashtadhyayi/blob/master/siddhantakaumudi/pada-3.1/3.1.134.md

Not sure if it is only for this page, or this issue is there for other pages or other vrttis too. Accidentally came across this issue, hence reporting it.

**Comment by vvasuki** [comment]
समीकृतम्।

किञ्च "सि.कौ. 8136" इति यत् 
https://github.com/sanskrit/ashtadhyayi/blob/master/siddhantakaumudi/pada-3.1/3.1.134.md इत्यस्मिन् दृश्यते, तदबद्धम्। (तद्धि स्रोत आसीद् दर्शनदोषस्य।)

**Comment by chandrasekharanr** [comment]
Fixed the typo, 8136 --> 1836.
