### ISSUE TITLE
vAsu digitization

### ISSUE THREAD

**Issue by vvasuki** [sanskrit/ashtadhyayi#44]
Requirements document here: https://docs.google.com/document/d/1FY402BKnbR41-Y6F2qK2FzKISBJWMV6y6OOCbg77BUA/edit#heading=h.og4crxklfyf1

कृष्णप्रसादेन वंशीकृष्ण इति सज्जनः परिचायितः कार्यार्थम्। तदीयकार्यपरिचये ऽद्य यतिष्यते।

cc @drdhaval2785 @neeleshb

**Comment by drdhaval2785** [comment]
Basu uses pratyâhâra
We should use current IAST standard mātrā, nadī, vadhū etc.

**Comment by drdhaval2785** [comment]
Any reason why we are not taking padani data? 
अत्-एङ् गुणः

**Comment by vvasuki** [comment]
> Basu uses pratyâhâra
>  We should use current IAST standard mātrā, nadī, vadhū etc.

Agreed. We can do a find replace in the end. Where diacritics are missing: Should I insist on ocr-corrector correcting it? Current thought is that I should not in the interest of faster progress - I've asked for special markup for sanskrit words in roman alphabet which will facilitate later mass replacement and gradual correction.


> Any reason why we are not taking padani data?
> अत्-एङ् गुणः

Already exists. Don't want to reduce progress unnecessarily.

**Comment by vvasuki** [comment]
अधुना ओमनदीपस्याकर्षणाभ्यर्थनं परीक्षितुम् उचितम् - https://github.com/sanskrit/ashtadhyayi/pull/46/files ।

**Comment by vvasuki** [comment]
https://github.com/sanskrit/ashtadhyayi/pull/47 इत्यत्र प्रतिस्पन्दो दीयताम्।

**Comment by vvasuki** [comment]
https://github.com/sanskrit/ashtadhyayi/pulls?q=is%3Aopen+is%3Apr ityatra svābhiprāyaṁ dātum ucitam.

**Comment by vvasuki** [comment]
@neeleshb has ingested this data, with some defects, which I will list as issuses at https://github.com/ashtadhyayi-com/data/issues since people seem to be contributing corrections there.
