### ISSUE TITLE
Foreign characters in bAlamanoramA

### ISSUE THREAD

**Issue by chandrasekharanr** [sanskrit/ashtadhyayi#8]
There are some foreign characters (such as �) in the bAlamanoramA text. For example, in https://github.com/sanskrit/ashtadhyayi/blob/master/balamanorama/pada-8.2/8.2.2.md

This should have been tackled in many of the previous texts.

**Comment by vvasuki** [comment]
http://www.babelstone.co.uk/Unicode/whatisit.html identifies � as the  U+FFFD : REPLACEMENT CHARACTER

**Comment by vvasuki** [comment]
The fix to https://github.com/sanskrit/ashtadhyayi/issues/14 seems to have solved this.
